# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  name: Default
steps:

    
- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
     targetType: 'inline'
     script: |
          export SRCCLR_SCM_URI=https://github.com/ashynavad-git/SCA.git
          export SRCCLR_API_TOKEN="1d618947-31f4-47a4-9ba7-11172c8e6c78"
          export SRCCLR_SCM_REF=master
          export SRCCLR_SCM_REV="Amit"
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor
  continueOnError: true
  env:
    SRCCLR_API_TOKEN: 1d618947-31f4-47a4-9ba7-11172c8e6c78
