# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  name: Default
steps:
- task: VeracodeCommunityScaAdoExtension@1
  inputs:
    scanType: 'url'
    scanTarget: 'https://github.com/vengamambha/Azure'
    appName: 'Azure'
    minCVSS: '0'
  env:
    SRCCLR_API_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDAyMjE5LCJleHAiOjE3MDI2NDkwNDgsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiJmYzljNzlmYy1kZGMwLTRhZDgtYWZjMi1mZDY4MTMwYjg1OGQiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.pbKqAxCP_DiwZWfkV5NGRxJF85U7Wug4dr-p20_RkUsUQwuJT0TexotgW_pBvZcL8qmmU3f3Mgvgb9cVQamnRGqcyvq5AfBEniheyHChG1edl8iS1noSp-k4JCZcMz8UM5VPCif4-dfFzpuDMAEIHqDsp_-tWp9W38YpGwccQ2Y